import { Trophy, Music, Gamepad2, Film, Book } from "lucide-react";

export const showcaseData = [
    {
        id: 1,
        category: "Sports",
        subcategory: "basketball",
        title: "Top 50 NBA Players",
        author: "@mbj",
        comment: "never lost in finals",
        icon: Trophy,
        color: {
            primary: "#f59e0b",
            secondary: "#d97706",
            accent: "#fbbf24",
        },
        timePeriod: "all-time" as const,
        hiearchy: "Top 50",
        position: { x: 10, y: 20 },
        rotation: -5,
        scale: 1.0,
    },
    {
        id: 2,
        category: "Games",
        subcategory: "video-games",
        title: "Best PC Games to play",
        author: "@gamer_pro",
        comment: "timeless classics that changed everything",
        timePeriod: "all-time" as const,
        hiearchy: "Top 50",
        icon: Gamepad2,
        color: {
            primary: "#8b5cf6",
            secondary: "#7c3aed",
            accent: "#a78bfa",
        },
        position: { x: 65, y: 15 },
        rotation: 3,
        scale: 0.9,
    },
    {
        id: 3,
        category: "Music",
        subcategory: "hip-hop",
        title: "Top Hip-Hop Tracks",
        author: "@music_head",
        timePeriod: "all-time" as const,
        hiearchy: "Top 50",
        comment: "beats that defined generations",
        icon: Music,
        color: {
            primary: "#ef4444",
            secondary: "#dc2626",
            accent: "#f87171",
        },
        position: { x: 20, y: 60 },
        rotation: 2,
        scale: 1.1,
        isBanned: true, // Special flag for banned card
    },
    {
        id: 4,
        category: "Stories",
        subcategory: "sci-fi",
        title: "Sci-Fi Masterpieces",
        author: "@film_buff",
        timePeriod: "all-time" as const,
        hiearchy: "Top 50",
        comment: "mind-bending cinema at its finest",
        icon: Film,
        color: {
            primary: "#06b6d4",
            secondary: "#0891b2",
            accent: "#22d3ee",
        },
        position: { x: 70, y: 65 },
        rotation: -3,
        scale: 0.85,
    },
    {
        id: 5,
        category: "Stories",
        subcategory: "fantasy",
        title: "Fantasy Novels",
        author: "@book_worm",
        timePeriod: "all-time" as const,
        hiearchy: "Top 50",
        comment: "worlds beyond imagination",
        icon: Book,
        color: {
            primary: "#10b981",
            secondary: "#059669",
            accent: "#34d399",
        },
        position: { x: 45, y: 40 },
        rotation: 1,
        scale: 0.95,
    },
];